version: "3"

services:

  icecast2:
    image: pltnk/icecast2
    container_name: icecast2
    restart: always
    ports:
      - 48000:8000
    volumes:
      - /dockerdata/apps/icecast/icecast.xml:/etc/icecast2/icecast.xml
